Update cudf groupby calls to explicitly set the sort option
rapidsai/cugraph pull request #1375
Opened 2021-02-02 23:22 UTC by jnke2016

set `sort=True` for all calls `groupby`

2021-02-03 20:31 UTC, BradReesWork commented on python/cugraph/bsp/traversal/bfs_bsp.py
> +        _a = one_hop.groupby(
this doesn't really need to be sorted - but it is okay since we should consider dropping the BSP folder in 0.19

2021-02-03 20:50 UTC, ChuckHastings requested changes
I suspect most of these do not require `sort=True` to be set.  Marked ones I specifically think can be skipped (although some I think might be able to be skipped).

I recommend setting `sort=False` and running the python unit tests.  If they all pass then we don't need `sort=True` on those calls.  If some of them fail you should be able to identify which of these might need the `sort=True`.

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/centrality/betweenness_centrality.py
> +        df = df.groupby(by=["src", "dst"], sort=True).sum().reset_index()
I would be surprised if this requires `sort=True`.  If you specify `sort=False` do any of the BC python tests fail?

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/number_map.py
> +                .groupby(src_col_names, sort=True)
This shouldn't require `sort=True`

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/number_map.py
> +                    .groupby(dst_col_names, sort=True)
This shouldn't require `sort=True`

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/number_map.py
> +                    self.col_names, sort=True).sum().sort_values(
This shouldn't require `sort=True`.  The groupby is followed by a sort later on the line.

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/number_map.py
> +                .groupby(src_col_names, sort=True)
This shouldn't require `sort=True`

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/number_map.py
> +                    .groupby(dst_col_names, sort=True)
This shouldn't require `sort=True`

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/number_map.py
> +                        self.col_names + ["hash", "partition"], sort=True
This does not require `sort=True`.  The groupby is followed explicitly by a sort.

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/number_map.py
> +                    lambda df: df.groupby("partition", sort=True).count()
This shouldn't require a `sort=True`.  We're only after a count, order doesn't matter.

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/symmetrize.py
> +            by=[src_name, dst_name], as_index=False, sort=True).min()
This shouldn't require `sort=True`.  Should check if the unit tests fail.

2021-02-03 20:50 UTC, ChuckHastings commented on python/cugraph/structure/symmetrize.py
> +        ddf.groupby(by=[src_name, dst_name], as_index=False, sort=True)
This shouldn't require sort=True. Should check if the unit tests fail.

2021-02-03 22:29 UTC, BradReesWork requested changes

2021-02-05 13:36 UTC, BradReesWork commented
after a review of the code by Joseph, it turns out that we are not dependent on needing a sort after the groupby call.  Since there is no need to update any code, this PR is being closed

2021-02-05 13:36 UTC, closed without merging