Add GHA to mark issues/prs as stale/rotten
rapidsai/cugraph pull request #1406
Opened 2021-02-12 10:15 UTC by Ethyling

Issues and PRs without activity for 30d will be marked as stale.
If there is no activity for 90d, they will be marked as rotten.

2021-02-12 13:06 UTC, BradReesWork commented
@Ethyling I agree with the process for marking PR, but marking issues basically means that we should not populate our backlog with things that we must get done

2021-02-12 13:12 UTC, BradReesWork requested changes
I do not agree this this PR and would like to know more reasoning behind it.

2021-02-12 13:47 UTC, BradReesWork approved these changes

2021-02-12 16:30 UTC, ajschmidt8 approved these changes

2021-02-12 18:50 UTC, BradReesWork commented
@gpucibot merge

2021-02-16 15:19 UTC, BradReesWork commented
@gpucibot merge

2021-02-16 15:21 UTC, Ethyling commented
> @gpucibot merge

There is an issue with the bot. We are working on it with @ajschmidt8

2021-02-16 16:58 UTC, Ethyling commented
@gpucibot merge

2021-02-16 17:03 UTC, Ethyling commented
Using this PR to resolve auto-merger issue: https://github.com/rapidsai/cugraph/pull/1408

2021-02-16 17:03 UTC, closed without merging