Move headers into cugraph dir
rapidsai/cugraph pull request #1582
Opened 2021-05-07 20:22 UTC by trxcllnt

This PR moves the headers in `cpp/include` into `cpp/include/cugraph` and updates C++ and Cython `#include` directives.

This change makes it easier for other libs to avoid naming conflicts with cuGraph public headers when linking `libcugraph.so`.

2021-05-07 21:11 UTC, ChuckHastings requested changes
There are some copyright dates causing failures.

Thanks for these edits!

2021-05-08 00:27 UTC, ChuckHastings approved these changes

2021-05-11 23:11 UTC, rlratzel approved these changes
LGTM, thanks for all the work here!

2021-05-12 14:39 UTC, BradReesWork commented
@gpucibot merge

2021-05-12 14:39 UTC, merged