Update UCX-Py version to 0.21
rapidsai/cugraph pull request #1650
Opened 2021-06-07 14:31 UTC by pentschev

2021-06-07 14:31 UTC, pentschev commented
Waiting for https://github.com/rapidsai/cugraph/pull/1649 to be merged first.

2021-06-07 14:55 UTC, rlratzel approved these changes
Thanks!

2021-06-07 15:03 UTC, ajschmidt8 requested changes

2021-06-07 15:03 UTC, ajschmidt8 commented on ci/release/update-version.sh
> +   sed_runner "s/ucx-py=0.21/ucx-py=0.21/g" ${FILE};
this is a no-op, so we can remove this line.

2021-06-07 15:17 UTC, BradReesWork approved these changes

2021-06-07 16:39 UTC, ajschmidt8 approved these changes

2021-06-07 16:39 UTC, ajschmidt8 commented
@gpucibot merge

2021-06-07 20:55 UTC, pentschev commented
Seems like there are several potentially legit cuGraph failures here, @rlratzel @BradReesWork could you take a look?

2021-06-07 21:02 UTC, pentschev commented
Oh, actually those seem to be because we're installing Dask/Distributed 2021.5.1, but we need 2021.6.0 or main for branch-21.08. It seems that this was covered by https://github.com/rapidsai/cugraph/blob/6aab21f01173b0b430197d15bdc700331ebe70c3/ci/gpu/build.sh#L75-L77 but something is downgrading them after that, perhaps we need https://github.com/rapidsai/dask-cuda/pull/645 first.

2021-06-07 21:32 UTC, pentschev commented
Actually no, https://github.com/rapidsai/dask-cuda/pull/645 won't help because it targets branch-21.06. I think something in the following block is downgrading Dask/Distributed: 
https://github.com/rapidsai/cugraph/blob/6aab21f01173b0b430197d15bdc700331ebe70c3/ci/gpu/build.sh#L89-L113

I'm not sure what package is the cause for downgrade, but perhaps we could move the Dask install after cuGraph? Also, this will need to wait for https://github.com/rapidsai/dask-cuda/pull/647, as https://github.com/rapidsai/dask-cuda/pull/645 just got merged and that pins 2021.5.1 in Dask-CUDA.

2021-06-09 21:58 UTC, pentschev commented
rerun tests

2021-06-09 21:58 UTC, pentschev commented
Rerunning tests now that cuDF and integration repo have been updated.

2021-06-10 01:27 UTC, ajschmidt8 commented
looks like this might be blocked by #1637 now. that one should hopefully be merged soon.

2021-06-14 18:08 UTC, ajschmidt8 commented
@pentschev, can you pull the latest changes here now that #1637 is merged?

2021-06-14 18:14 UTC, pentschev commented
> can you pull the latest changes here now that #1637 is merged?

Done.

2021-06-14 22:26 UTC, merged