Docs for RMAT
rapidsai/cugraph pull request #1735
Opened 2021-07-27 13:33 UTC by BradReesWork

Fixed indentations so that docs appear correctly

2021-07-28 14:44 UTC, rlratzel requested changes
Just a few typos.

2021-07-28 14:44 UTC, rlratzel commented on python/cugraph/generators/rmat.py
> +        Scale factor to set the number of verties in the graph Vertex IDs have
```suggestion
        Scale factor to set the number of vertices in the graph Vertex IDs have
```

2021-07-28 14:44 UTC, rlratzel commented on python/cugraph/generators/rmat.py
> +    S   eed value for the random number generator
```suggestion
    Seed value for the random number generator
```

2021-07-28 14:44 UTC, rlratzel commented on python/cugraph/generators/rmat.py
> +        or not (if set to `false`); scrambling vertx ID bits breaks correlation
```suggestion
        or not (if set to `false`); scrambling vertex ID bits breaks correlation
```

2021-07-28 14:44 UTC, rlratzel commented on python/cugraph/generators/rmat.py
> +        between vertex ID values and vertex degrees
```suggestion
        between vertex ID values and vertex degrees.
```

2021-07-28 15:11 UTC, jnke2016 reviewed
Nothing to add other than the few typo mentioned by Rick

2021-07-28 19:58 UTC, rlratzel approved these changes

2021-07-28 19:58 UTC, BradReesWork commented
@gpucibot merge

2021-07-29 13:08 UTC, BradReesWork commented
@gpucibot merge

2021-07-29 13:09 UTC, merged