Add new new raft symlink path to .gitignore
rapidsai/cugraph pull request #1808
Opened 2021-09-07 19:23 UTC by trxcllnt

2021-09-09 15:11 UTC, rlratzel requested changes
We have another python package now that uses raft the same way.

2021-09-09 15:11 UTC, rlratzel commented on .gitignore
> +python/cugraph/cugraph/raft
```suggestion
python/cugraph/cugraph/raft
python/pylibcugraph/pylibcugraph/raft
```

2021-09-09 17:48 UTC, rlratzel approved these changes

2021-09-09 17:48 UTC, rlratzel commented
Thanks for this update!

2021-09-10 13:24 UTC, BradReesWork approved these changes

2021-09-10 13:24 UTC, BradReesWork commented
@gpucibot merge

2021-09-10 13:24 UTC, merged