Count if e test
rapidsai/cugraph pull request #1821
Opened 2021-09-15 16:25 UTC by kaatish

This PR adds multi-gpu testing for count_if_e primitive.

2021-09-15 17:02 UTC, seunghwak approved these changes
Looks great!

2021-09-15 20:57 UTC, seunghwak commented
rerun tests

2021-09-16 14:49 UTC, kaatish commented
rerun tests

2021-09-19 02:29 UTC, ChuckHastings commented
rerun tests

2021-09-19 02:35 UTC, ChuckHastings requested changes

2021-09-19 02:35 UTC, ChuckHastings commented on cpp/tests/prims/mg_count_if_e.cu
> +        input_usecase.template construct_graph<vertex_t, edge_t, weight_t, store_transposed, false>(
I just changed this in a PR that got merged.  If you merge the latest 21.10 you'll find this doesn't compile.

You need to change this call to something like:
`cugraph::test::construct_graph<vertex_t, edge_t, weight_t, store_transposed, false>(handle, input_usecase, true, false)`

2021-09-19 02:35 UTC, ChuckHastings commented on cpp/tests/prims/mg_count_if_e.cu
> +      input_usecase.template construct_graph<vertex_t, edge_t, weight_t, store_transposed, true>(
I just changed this in a PR that got merged. If you merge the latest 21.10 you'll find this doesn't compile.

This call should be something like:
`cugraph::test::construct_graph<vertex_t, edge_t, weight_t, store_transposed, true>(handle, input_usecase, prims_usecase.test_weighted, true);`

2021-09-20 17:11 UTC, ChuckHastings commented
rerun tests

2021-09-20 20:04 UTC, ChuckHastings approved these changes

2021-09-21 13:12 UTC, BradReesWork commented
@gpucibot merge

2021-09-21 13:12 UTC, merged