Fix README example
rapidsai/cugraph pull request #1981
Opened 2021-12-05 20:56 UTC by gitbuda

2021-12-05 20:56 UTC, GPUtester commented
Can one of the admins verify this patch?

2021-12-05 20:56 UTC, GPUtester commented
Can one of the admins verify this patch?

2021-12-06 14:40 UTC, BradReesWork approved these changes

2021-12-14 15:38 UTC, rlratzel requested changes
Thanks for fixing the README. I noticed a minor problem with the CHANGELOG that needs to be fixed, but otherwise this looks good.

2021-12-14 15:38 UTC, rlratzel commented on CHANGELOG.md
> +>>>>>>> origin/branch-0.17
Looks like some markers from a merge conflict were left in and still need to be removed.

2022-01-11 16:37 UTC, rlratzel approved these changes

2022-01-11 16:39 UTC, BradReesWork commented
rerun tests

2022-01-11 18:58 UTC, ajschmidt8 commented
ok to test

2022-01-11 19:25 UTC, merged