[WIP] [FEA] add libcugraphops as a dependency of cugraph
rapidsai/cugraph pull request #2019
Opened 2022-01-19 17:16 UTC by MatthiasKohl

We need to do several things:
- Add libcugraphops to conda (both in the cugraph recipe as well as build environment)
- Add libcugraphops to cmake (I added a new thirdparty include here)
- Ensure that the right headers and objects are added in cmake

For now, this is a work in progress since libcugraphops doesn't seem available on anaconda yet.

2022-01-20 13:51 UTC, BradReesWork approved these changes

2022-01-20 14:28 UTC, ajschmidt8 commented
Please consider using GitHub's _Draft PR_ feature instead of `WIP` tags in the future. Draft PRs have the benefit of preventing notifications to `codeowners` until PRs are marked _Ready for Review_, which helps cut down on excessive notifications for PRs that are still being worked on. CI will still run on Draft PRs.

Some useful information about Draft PRs:

- https://github.blog/2019-02-14-introducing-draft-pull-requests/
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

2022-01-31 18:10 UTC, MatthiasKohl commented
@ajschmidt8 sorry about this, I wasn't aware of the feature, I'll try to use it from now on

2022-02-01 16:19 UTC, BradReesWork commented
rerun tests

2022-02-02 17:29 UTC, BradReesWork commented
rerun tests

2022-02-03 14:01 UTC, robertmaynard approved these changes
CMake changes LGTM

2022-02-03 14:34 UTC, BradReesWork approved these changes

2022-02-07 15:40 UTC, Ethyling requested changes

2022-02-07 18:08 UTC, MatthiasKohl commented on conda/environments/cugraph_dev_cuda11.0.yml
> +- rapidsai-nightly/label/testing
done.

2022-02-09 17:45 UTC, ChuckHastings commented
rerun tests

2022-02-10 04:20 UTC, ChuckHastings commented
rerun tests

2022-02-11 12:32 UTC, MatthiasKohl commented
rerun tests

2022-02-12 12:56 UTC, rlratzel approved these changes

2022-02-12 13:27 UTC, Ethyling approved these changes

2022-02-12 13:32 UTC, rlratzel commented
@gpucibot merge

2022-02-12 13:32 UTC, merged