Updating issue template and missing docs
rapidsai/cugraph pull request #2211
Opened 2022-04-07 16:42 UTC by BradReesWork

Templates
* added acceptance criterias
* dropped enhancement as an issue type

Doc
* adding missing references
* adding sampling

2022-04-07 18:58 UTC, ajschmidt8 approved these changes

2022-04-13 20:14 UTC, rlratzel requested changes

2022-04-13 20:14 UTC, rlratzel commented on .github/ISSUE_TEMPLATE/feature_request.md
> +  - [] Test cases at each layer
```suggestion
  - [] Test cases at each layer (for MG tests, a note in the PR description indicating the new/existing MG tests were run and passed)
```

2022-04-13 20:14 UTC, rlratzel commented on docs/cugraph/source/api_docs/sampling.rst
> +   cugraph.dask.sampling.neighborhood_sampling.EXPERIMENTAL__uniform_neighborhood
```suggestion
   cugraph.experimental.dask.uniform_neighborhood_sampling
```

2022-04-14 16:13 UTC, ChuckHastings approved these changes

2022-04-15 13:32 UTC, BradReesWork commented
@gpucibot merge

2022-04-15 13:32 UTC, merged