Allow `cugraph` to be imported in an SG env for SG algorithms
rapidsai/cugraph pull request #2241
Opened 2022-04-21 23:57 UTC by betochimas

This PR aims to directly resolve #2113, and allows for cugraph to be imported without errors in environments with only a single GPU

2022-04-26 16:53 UTC, betochimas commented
rerun tests

2022-04-26 16:53 UTC, betochimas commented
rerun tests

2022-04-29 21:13 UTC, rlratzel requested changes

2022-04-29 21:13 UTC, rlratzel commented on ci/test.sh
> +# pytest --cache-clear --junitxml=${CUGRAPH_ROOT}/junit-cugraph-pytests.xml -v --cov-config=.coveragerc --cov=cugraph --cov-report=xml:${WORKSPACE}/python/cugraph/cugraph-coverage.xml --cov-report te
You can remove the commented out line now. You might also add a comment explaining why rmat is also being skipped.

2022-04-29 21:13 UTC, rlratzel commented on python/cugraph/cugraph/dask/common/input_utils.py
> +        raise ModuleNotFoundError
This should just be a `raise`, which re-raises the original exception.
```suggestion
        raise 
```
If you do a `raise ModuleNotFoundError`, you lose the original information (mainly the missing module name)

2022-05-03 20:26 UTC, rlratzel approved these changes

2022-05-03 20:38 UTC, ajschmidt8 approved these changes
Approving `ops-codeowner` file changes

2022-05-03 21:47 UTC, betochimas commented
rerun tests

2022-05-04 00:14 UTC, rlratzel commented
@gpucibot merge

2022-05-04 00:14 UTC, merged