fixes BUG 2275
rapidsai/cugraph pull request #2279
Opened 2022-05-17 13:43 UTC by BradReesWork

Fixes the bug where "to_pandas_edgelist" ignores output column names

2022-05-18 21:08 UTC, BradReesWork commented
rerun tests

2022-05-19 17:54 UTC, jnke2016 approved these changes
Looks good to me

2022-05-20 17:35 UTC, rlratzel requested changes

2022-05-20 17:59 UTC, BradReesWork commented on python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py
> +    def to_pandas_edgelist(self, source='src', destination='dst',
true.  But the defaults really were not the default values used in the data structures.   
I'll update the doc string

2022-05-20 20:25 UTC, betochimas commented
Observing from the current CI failures in `test_convert_matrix.py` and `test_multigraph.py`, some columns need to be renamed after this API change. In multiple tests from test_convert_matrix, the columns of res_pdf could be renamed:
`res_pdf = res_pdf.rename(columns={"source": "src", "destination": "dst"})`

2022-05-20 21:30 UTC, jnke2016 reviewed
It looks like this small change has some ramification on some tests

2022-05-23 16:47 UTC, BradReesWork commented
the test in `test_convert_matrix` assume that the returned column names are "src", "dst", and "weight", so the updated function will help ensure that.  and I  fixed all the calls to DiGraph

2022-05-23 20:53 UTC, rlratzel approved these changes

2022-05-24 12:56 UTC, BradReesWork commented
@gpucibot merge

2022-05-24 12:56 UTC, merged