Don't store redundant columns in PropertyGraph Dataframes
rapidsai/cugraph pull request #2449
Opened 2022-07-27 04:39 UTC by eriknw

The main purpose of this is to reduce memory usage.

Closes #2400

I still need to update MG tests.

I'll also remove the in-code assertions, since they won't always be True, because a column name could have previously been used as a property. Nevertheless, seeing these assertions pass should give us warm-fuzzies :)

2022-07-28 05:24 UTC, eriknw commented
One thing I don't like about the current state of this PR is that it makes the user use our column names for source, dest, etc. in the query string.

What if `"_SRC_ == 4"` was instead specified as e.g. `"{src} == 4"` (or `f"{{src}} == 4"` if the user was using an f-string).  Any other syntax or spelling we should consider?

2022-07-28 16:15 UTC, rlratzel approved these changes
Looks good. There might be places in here that will be affected by the outcome of how we want to handle the "internal" column names in output and tests, but no need to change anything now.

2022-07-28 16:46 UTC, alexbarghi-nv approved these changes

2022-07-28 18:12 UTC, VibhuJawa requested changes
Have requested changes to drop inpace for cudf columns.  LGTM otherwise.

2022-07-28 21:09 UTC, eriknw commented on python/cugraph/cugraph/structure/property_graph.py
> +        tmp_df = tmp_df.drop(labels=column_names_to_drop, axis=1)
Fair question.  I generally don't like to use `inplace=True`.   It often makes code harder to debug, and the performance or memory usage benefit is usually negligible.  Many pandas devs have been saying "don't use inplace" and considering deprecating it for years: https://github.com/pandas-dev/pandas/issues/16529

I don't know about `cudf`.  Does using `inplace=True` have tangible benefits when using `cudf`?

2022-07-28 21:19 UTC, VibhuJawa commented on python/cugraph/cugraph/structure/property_graph.py
> +        tmp_df = tmp_df.drop(labels=column_names_to_drop, axis=1)
At least, this used to be the case where using `inplace=True`   had tangible  benefits in terms of memory usage.  @galipremsagar  , Would you know if that still holds true ?

2022-07-28 21:24 UTC, galipremsagar commented on python/cugraph/cugraph/structure/property_graph.py
> +        tmp_df = tmp_df.drop(labels=column_names_to_drop, axis=1)
Using `inplace=True` will avoid making a new copy and operates on the same data frame itself. So I expect it to be a bit performant in this case.

2022-07-29 04:52 UTC, VibhuJawa approved these changes
LGTM. Thanks Erik

2022-07-30 21:38 UTC, eriknw commented
Test failures are now the same as seen in other PRs:
```
    from cupyx.scipy.sparse.coo import coo_matrix as cp_coo_matrix
E   ModuleNotFoundError: No module named 'cupyx.scipy.sparse.coo'
```

2022-08-02 20:33 UTC, BradReesWork approved these changes

2022-08-02 20:34 UTC, BradReesWork commented
@gpucibot merge

2022-08-02 20:34 UTC, merged