Fix MG PLC algos intermittent hang
rapidsai/cugraph pull request #2607
Opened 2022-08-23 01:36 UTC by jnke2016

Dask doesn't always release some of the inactive futures fast enough. This can be problematic when running the same `algo` several times with the same `PLC graph` because those futures can be cache in the next iteration causing a hang if some get released midway.

This PR manually delete inactive futures.
closes #2568

2022-08-25 22:56 UTC, rlratzel approved these changes

2022-08-26 01:48 UTC, VibhuJawa requested changes
I am requesting to delete `cudf_result`, looks good otherwise.

2022-08-26 01:48 UTC, VibhuJawa commented on python/cugraph/cugraph/dask/cores/core_number.py
> +    del result
I think removing `result` is still a good practice as when `cudf_result`  is completed  we will still have `result` in memory so from a memory relief standpoint it makes sense.

2022-08-26 01:48 UTC, VibhuJawa commented on python/cugraph/cugraph/dask/cores/core_number.py
> +
I suggest we also remove `cudf_result` here to save on memory . We have a renumbered call after this so `result` does not go out of scope immediately.

2022-08-27 01:42 UTC, jnke2016 commented
rerun tests

2022-08-27 03:16 UTC, jnke2016 commented
rerun tests

2022-08-29 20:26 UTC, jnke2016 commented
rerun tests

2022-08-31 01:50 UTC, jnke2016 commented
rerun tests

2022-08-31 13:35 UTC, ajschmidt8 approved these changes

2022-08-31 16:00 UTC, merged