Allow users to provide their own edge IDS to PropertyGraph
rapidsai/cugraph pull request #2757
Opened 2022-09-29 05:30 UTC by eriknw

Closes #2565

Should we try to avoid creating conflicting edge IDs (for example, when user doesn't provides _all_ edge IDs).  Should we expose `last_edge_id`.

2022-09-29 17:55 UTC, VibhuJawa requested changes
The overall changes look good  but I think we should ask the user provide  edge_ids if they do it once and  also expose last_edge_id.

https://github.com/rapidsai/cugraph/pull/2757#issue-1390279530

2022-09-29 19:25 UTC, eriknw commented
Case 1:
- User adds data with edge ids
- then user adds data w/o edge ids

Case 2:
- User adds data w/o edge ids
- then user adds data with edge ids

@VibhuJawa, do I understand your comment correctly that you want to support case 2, but not case 1?

We can handle case 1 by taking the max of the user-provided edge ids (as is currently done in this PR).  Not supporting this lets us avoid taking the max.

We could support case 2 by trusting the user.  Giving them the last (i.e., max) edge id could be a way to give them the tool to do this.  Exposing this value once again requires taking the max of the user-provided edge ids.

So, basically, all options are available to us:
- don't support case 1 or 2
  - no need to call max
- support case 1 only (current state of PR)
  - calls max, probably no need to expose last_edge_id
- support case 2 only
  - only call max if we also expose last edge id
- support cases 1 and 2
  - calls max, can expose last_edge_id

2022-09-30 18:59 UTC, VibhuJawa commented
> support case 1 only (current state of PR)
calls max, probably no need to expose last_edge_id

I think this good for now .  The usecase i think this is useful is when we want to create new edges like adding self-loops etc . 

Can we create a feature request for other cases so that we can track and prioritize them as need arises.

2022-10-02 18:32 UTC, VibhuJawa approved these changes
LGTM

2022-10-03 19:39 UTC, rlratzel commented
We had further discussion about case 1/case 2 offline, captured [here](https://github.com/rapidsai/cugraph/issues/2565#issuecomment-1265940964).

2022-10-03 19:42 UTC, rlratzel reviewed
Looks good, I just had one question, then I'll re-review after the changes from [this conversation](https://github.com/rapidsai/cugraph/issues/2565#issuecomment-1265940964) are done.

2022-10-03 21:03 UTC, eriknw commented on python/cugraph/cugraph/dask/structure/mg_property_graph.py
> +            tmp_df.persist()
ha, I just caught (and fixed) this too (and I thought I had already fixed this, but I think merging with squashed PRs isn't as smart as merging non-squished PRs, so maybe it snuck back in).  `tmp_df = tmp_df.persist()` is the correct spelling.  `tmp_df.persist()` without assignment is wasted work.

It's recommended to persist after setting index, and I think sometimes before setting index too.  I think we'll want to look more closely at usage of `persist` and operations like `set_index` in the coming months as we scale to larger data sets.

2022-10-03 23:00 UTC, rlratzel approved these changes
LGTM, especially the added test coverage.

2022-10-04 01:46 UTC, rlratzel commented
@gpucibot merge

2022-10-04 01:46 UTC, merged

2022-10-04 02:50 UTC, eriknw commented on python/cugraph/cugraph/dask/structure/mg_property_graph.py
> +            tmp_df.persist()
See: https://docs.dask.org/en/stable/dataframe-best-practices.html#persist-intelligently