Create a notebook comparing nx and cuGraph using synthetic data
rapidsai/cugraph pull request #3135
Opened 2023-01-12 15:49 UTC by acostadon

Rapids visualization group asked for some data comparing cuGraph algos to nx.
Used Release notebook as a base, replaced datasets with RMAT data generator.

Closes #3134

2023-01-13 16:14 UTC, BradReesWork commented
minor text changed needed

2023-01-13 16:15 UTC, BradReesWork requested changes
some text needs to be updated and the generator fixed

2023-01-13 19:06 UTC, exactlyallan commented
From a content perspective, this notebook works well for the website benchmark. For viz: https://github.com/rapidsai/cuml/pull/5103#issuecomment-1382261796

2023-01-24 17:06 UTC, BradReesWork commented
The notebook need a header block at the top explain what it is doing

2023-01-24 17:11 UTC, BradReesWork commented
Cell 3:  The names of the datasets are confusing.  What not "data_scale_11" instead of "data_11th" .  I'm not sure what the "11th" is

2023-01-24 17:11 UTC, BradReesWork commented
Cel 4 - the text is wrong - this is not a data reader

2023-01-24 17:13 UTC, BradReesWork commented
cell 4:
print('Generating a dataframe of ' + str(len(_gdf)) + '...')
should be past tense
print(f'Generated {str(len(_gdf))} edges' )

2023-01-24 17:14 UTC, BradReesWork commented
Cell 5 - why not combine the two cuGraph creates into one and have a "direction" flag passed in?

It used to be two functions since there was Graph and DiGraph, but that is no longer the case

2023-01-24 17:15 UTC, BradReesWork commented
Cell 6 - Katz still have the Nx object function

2023-01-24 17:19 UTC, BradReesWork commented
Cell 12:  PageRank

```
    _G = create_cu_directed_graph(_df, transpose=True)
    if _G.is_directed():
        _G = _G.to_undirected()
```
why not just create an undirected graph?

2023-01-24 17:26 UTC, BradReesWork commented
Cell 3:
What are the Scale number so small?   We want to compare against larger graphs,   max should be scale 25 

Do Scales:  (or pick 3 or 4)
10
14
16
19
22
24
25

2023-01-24 18:52 UTC, BradReesWork requested changes
see comments

2023-01-27 19:16 UTC, BradReesWork approved these changes

2023-01-27 20:19 UTC, BradReesWork commented
/merge

2023-01-27 20:19 UTC, merged