add docs_build step
rapidsai/cugraph pull request #3157
Opened 2023-01-18 17:56 UTC by AyodeAwe

The PR adds a `docs_build `process to the PR and Build workflows for this repository. The generated docs are synced to s3 for only the build workflows.

2023-01-27 15:40 UTC, BradReesWork commented
@AyodeAwe there is a merge conflict

2023-01-27 15:42 UTC, BradReesWork approved these changes

2023-01-27 21:33 UTC, ajschmidt8 requested changes

2023-01-27 21:33 UTC, ajschmidt8 commented on ci/build_docs.sh
> +  aws s3 sync --delete docs/cugraph/_text "s3://rapidsai-docs/cugraph/${VERSION_NUMBER}/text"
```suggestion
  aws s3 sync --delete docs/cugraph/_text "s3://rapidsai-docs/cugraph/${VERSION_NUMBER}/txt"
```

This S3 path should be consistent with the path used in the other PRs.

e.g. https://github.com/rapidsai/rmm/blob/7662b2411684079c58a1dc3d43d625b4a683f93f/ci/build_docs.sh#L44

2023-01-27 21:33 UTC, ajschmidt8 commented on compare.yaml
> +# Dependency list for https://github.com/rapidsai/dependency-file-generator
This file looks like it was accidentally committed.

2023-01-29 17:04 UTC, AyodeAwe commented
```
Handler <function process_generate_options at 0x7f26ae8f3ee0> for event 'builder-inited' threw an exception (exception: no module named cugraph_dgl)
```
I get this error locally as well.


`rapids-mamba-retry install "${PYTHON_CHANNEL}/linux-64/cugraph-dgl-*.tar.bz2"`
This bypass (which circumvents the `cudatoolkit` version mismatch) doesn't seem to work anymore for some reason. An interesting find while debugging locally is the following error when I try to import the cugraph_dgl module in a python script:

```
>>> import cugraph_dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/docs/lib/python3.8/site-packages/cugraph_dgl/__init__.py", line 20, in <module>
    import cugraph_dgl.nn
  File "/opt/conda/envs/docs/lib/python3.8/site-packages/cugraph_dgl/nn/__init__.py", line 13, in <module>
    from .conv import *  # noqa
  File "/opt/conda/envs/docs/lib/python3.8/site-packages/cugraph_dgl/nn/conv/__init__.py", line 13, in <module>
    from .gatconv import GATConv
  File "/opt/conda/envs/docs/lib/python3.8/site-packages/cugraph_dgl/nn/conv/gatconv.py", line 27, in <module>
    class GATConv(nn.Module):
  File "/opt/conda/envs/docs/lib/python3.8/site-packages/cugraph_dgl/nn/conv/gatconv.py", line 120, in GATConv
    g: dgl.DGLHeteroGraph,
  File "/opt/conda/envs/docs/lib/python3.8/site-packages/cugraph/utilities/utils.py", line 403, in __getattr__
    raise RuntimeError(f"This feature requires the {self.name} " "package/module")
RuntimeError: This feature requires the dgl package/module
```

2023-01-30 16:05 UTC, AyodeAwe commented
Regarding this [comment](https://github.com/rapidsai/cugraph/pull/3157#issuecomment-1407716999), a `pip install dgl` gets rid of that error but a new error pops up:

```
Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x7f723bdb7ee0> for event 'builder-inited' threw an exception (exception: no module named cugraph_pyg.loader.dispatch)
```

2023-02-13 23:44 UTC, ajschmidt8 commented on .github/workflows/build.yaml
> +    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@cuda-118
```suggestion
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@branch-23.04
```

2023-02-13 23:44 UTC, ajschmidt8 commented on .github/workflows/pr.yaml
> +    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@cuda-118
```suggestion
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@branch-23.04
```

2023-02-21 21:21 UTC, ajschmidt8 requested changes

2023-02-21 21:21 UTC, ajschmidt8 commented on ci/build_docs.sh
> +# Build Doxygen docs
```suggestion
```

We can remove this comment since it doesn't provide any value.

2023-02-21 21:21 UTC, ajschmidt8 commented on ci/build_docs.sh
> +# Build Python docs
```suggestion
```

We can remove this comment since it doesn't provide any value.

2023-02-21 21:21 UTC, ajschmidt8 commented on dependencies.yaml
> +          - sphinx_rtd_theme
```suggestion
```

We know from the [contents of conf.py](https://github.com/AyodeAwe/cugraph/blob/10c37b3932a5b1bda871bcabaa6d3cf2daf27d95/docs/cugraph/source/conf.py#L108) that `cugraph` uses the `pydata-sphinx-theme`.

Therefore we don't also need to install the `sphinx_rtd_theme`.

2023-02-21 21:26 UTC, ajschmidt8 approved these changes

2023-02-22 22:37 UTC, AyodeAwe commented
@VibhuJawa how should this style check failure be handled? The error showed up after we imported [your patch](https://github.com/rapidsai/cugraph/pull/3157/commits/31bf9558ef5e56fdae1dee275f45f9a33806e5fe):

```
python/cugraph-dgl/cugraph_dgl/dataloading/dataloader.py:144:38: F821 undefined name 'create_tensorized_dataset'
```

https://github.com/rapidsai/cugraph/actions/runs/4247522209/jobs/7385666170

2023-02-22 22:48 UTC, VibhuJawa commented
> @VibhuJawa how should this style check failure be handled? The error showed up after we imported [your patch](https://github.com/rapidsai/cugraph/pull/3157/commits/31bf9558ef5e56fdae1dee275f45f9a33806e5fe):
> 
> ```
> python/cugraph-dgl/cugraph_dgl/dataloading/dataloader.py:144:38: F821 undefined name 'create_tensorized_dataset'
> ```
> 
> https://github.com/rapidsai/cugraph/actions/runs/4247522209/jobs/7385666170
> 
> cc: @ajschmidt8

This  [line](https://github.com/rapidsai/cugraph/pull/3157/files#diff-90e104d897a4c013ed2a0277850b6ca609e86605dccf38da479b6a066c5e45feR144)  `create_tensorized_dataset` should have been `dgl.dataloading.create_tensorized_dataset`  like in this [patch](https://github.com/rapidsai/cugraph/pull/3157/commits/31bf9558ef5e56fdae1dee275f45f9a33806e5fe#diff-90e104d897a4c013ed2a0277850b6ca609e86605dccf38da479b6a066c5e45feR144) . .

I think we had a bad merge which erased it. Anyways, add it and you should be good to go.

2023-02-27 17:15 UTC, BradReesWork approved these changes

2023-02-27 17:17 UTC, rlratzel approved these changes
I see that @VibhuJawa looked over some of the non-docs related changes to cugraph-dgl files, so I'm assuming those are supposed to be in this PR.

2023-02-27 18:05 UTC, ajschmidt8 commented
> I see that @VibhuJawa looked over some of the non-docs related changes to cugraph-dgl files, so I'm assuming those are supposed to be in this PR.

Yes. Good call out, @rlratzel. There were some import issues that required a patch from Vibhu which we included.

2023-02-27 19:04 UTC, VibhuJawa approved these changes
LGTM

2023-02-27 19:05 UTC, VibhuJawa commented
@rlratzel , Yup those changes allow building `cugraph-dgl` in a environment without  `dgl` and `pytorch` . The changes look good to me.  Approved the PR too.

2023-02-28 17:49 UTC, AyodeAwe commented
/merge

2023-02-28 17:49 UTC, merged