Add MG implementation of induced subgraph
rapidsai/cugraph pull request #3391
Opened 2023-03-29 14:56 UTC by jnke2016

This PR adds an MG implementation of induced subgraph by leveraging the CAPI

closes #2535 
closes #2536

2023-03-30 17:42 UTC, ChuckHastings approved these changes

2023-03-31 21:10 UTC, rlratzel requested changes
Can you also add deprecatino warnings for `cugraph.subgraph` so we can start the process of removing that API, which is now redundant?

2023-03-31 21:10 UTC, rlratzel commented on python/cugraph/cugraph/dask/community/induced_subgraph.py
> +def induced_subgraph(input_graph, vertices, offsets=None):
Can you also add type annotations?

2023-03-31 21:10 UTC, rlratzel commented on python/cugraph/cugraph/dask/community/induced_subgraph.py
> +    offsets : cupy array
Is the type here supposed to be `cudf.Series` ? Just asking because you create a `cudf.Series` if `offsets` is None below.

2023-03-31 22:07 UTC, jnke2016 commented on python/cugraph/cugraph/dask/community/induced_subgraph.py
> +def induced_subgraph(input_graph, vertices, offsets=None):
Addressed

2023-04-03 20:56 UTC, rlratzel approved these changes

2023-04-03 20:58 UTC, rlratzel commented
/merge

2023-04-03 20:58 UTC, merged