[IMP] Sample with Offsets in the Bulk Sampler
rapidsai/cugraph pull request #3524
Opened 2023-04-28 21:38 UTC by alexbarghi-nv

Resolves #3318 
Resolves #3385 

Updates the bulk sampler to use the offsets returned by the `uniform_neighbor_sample` call, and take advantage of the pre-partitioned data returned from C++ to avoid repartitioning and scanning, and also to reduce the number of files written.  This PR is expected to significantly improve memory and compute time for bulk sampling.

2023-05-05 20:57 UTC, rlratzel requested changes
Mostly minor things.

2023-05-05 20:57 UTC, rlratzel commented on python/cugraph-pyg/cugraph_pyg/loader/cugraph_node_loader.py
> +            self.__input_files.reverse()
curious why this is necessary.

2023-05-05 20:57 UTC, rlratzel commented on python/cugraph-pyg/cugraph_pyg/loader/cugraph_node_loader.py
> +        print(self.__input_files)
I'm assuming we don't want prints here?

2023-05-05 20:57 UTC, rlratzel commented on python/cugraph-pyg/cugraph_pyg/loader/cugraph_node_loader.py
> +            print("fname: ", fname)
same here, another debug print?

2023-05-05 20:57 UTC, rlratzel commented on python/cugraph/cugraph/dask/community/egonet.py
> +    print(cp_weight)
debug print?

I see a few others, but I'll just re-review instead of pointing each one out.

2023-05-05 20:57 UTC, rlratzel commented on python/cugraph/cugraph/dask/traversal/sssp.py
> +        raise RuntimeError(err_msg)
This is okay, but would `ValueError` be better?

2023-05-05 20:57 UTC, rlratzel commented on python/cugraph/cugraph/gnn/data_loading/bulk_sampler.py
> +            ] = self.__get_label_to_output_comm_rank(min_batch_id, max_batch_id)
I'm assuming `black` did this, but it seems like this formatting could be nicer :)

2023-05-05 20:57 UTC, rlratzel commented on python/cugraph/cugraph/tests/structure/test_graph.py
> +@pytest.mark.parametrize(
Nice!

2023-05-08 15:33 UTC, alexbarghi-nv commented on python/cugraph/cugraph/tests/traversal/test_sssp.py
> +    print(M)
I just dropped it

2023-05-08 15:37 UTC, alexbarghi-nv commented on python/cugraph/cugraph/traversal/sssp.py
> +            "'BFS' should be used instead of 'SSSP' for unweighted graphs."
done

2023-05-08 19:42 UTC, rlratzel approved these changes
LGTM, thanks

2023-05-09 19:05 UTC, rlratzel commented
/merge

2023-05-09 20:36 UTC, alexbarghi-nv commented
/merge

2023-05-10 02:35 UTC, merged