Change the renumber_sampled_edgelist function behavior.
rapidsai/cugraph pull request #3762
Opened 2023-08-02 18:04 UTC by seunghwak

There was a misalignment between the `renumber_sampled_edgelist` function behavior and what PyG and DGL need.

This PR fixes this.

2023-08-02 20:27 UTC, alexbarghi-nv commented
@seunghwak is this PR ready yet?  I'm still seeing the wrong behavior after trying sampling with the PR.

2023-08-03 14:34 UTC, alexbarghi-nv requested changes
Looks good, just the issue with chunk size.  Benchmarks succeed when ensuring `num_chunks` is >=1

2023-08-03 14:34 UTC, alexbarghi-nv commented on cpp/src/sampling/renumber_sampled_edgelist_impl.cuh
> +    auto chunk_size = (num_labels + (num_chunks - 1)) / num_chunks;
```suggestion
    auto chunk_size = (num_labels + (num_chunks - 1)) / num_chunks;
    if(num_chunks < 1) {
      num_chunks = 1;
    }
```

2023-08-03 15:56 UTC, alexbarghi-nv commented on cpp/src/sampling/renumber_sampled_edgelist_impl.cuh
> +    auto chunk_size = (num_labels + (num_chunks - 1)) / num_chunks;
This has been fixed now.

2023-08-03 16:41 UTC, alexbarghi-nv approved these changes
👍

2023-08-03 16:46 UTC, ChuckHastings approved these changes

2023-08-03 16:49 UTC, ChuckHastings commented
/merge

2023-08-03 21:56 UTC, merged