Use new `raft::compiled_static` targets
rapidsai/cugraph pull request #3842
Opened 2023-09-02 00:01 UTC by divyegala

https://github.com/rapidsai/raft/pull/1746 added static targets for RAFT that can be used directly now instead of building RAFT static explicitly

2023-09-05 21:07 UTC, robertmaynard requested changes

2023-09-05 21:07 UTC, robertmaynard commented on cpp/CMakeLists.txt
> +set(COMPILED_RAFT_LIB_STATIC "")
```suggestion
```

2023-09-05 21:07 UTC, robertmaynard commented on cpp/CMakeLists.txt
> +    set(COMPILED_RAFT_LIB_STATIC raft::compiled_static)
```suggestion
    set(COMPILED_RAFT_LIB raft::compiled_static)
```

2023-09-06 14:45 UTC, ChuckHastings approved these changes

2023-09-06 14:45 UTC, ChuckHastings commented
/merge

2023-09-06 14:45 UTC, merged