new build all option
rapidsai/cugraph pull request #3916
Opened 2023-10-05 18:16 UTC by BradReesWork

option to build all

Renamed the old buildAll function to buildDefault 
Added a check for the "all" argument

2023-10-10 22:16 UTC, jnke2016 approved these changes

2023-10-11 17:39 UTC, rlratzel requested changes

2023-10-11 17:39 UTC, rlratzel commented on build.sh
> +if buildDefault || hasArg libcugraph_etl || hasArg all; then
Do we want to build `libcugraph_etl` by default?  I could go either way.

2023-10-11 17:39 UTC, rlratzel commented on build.sh
> + default action (no args) is to build and install 'libcugraph' then 'pylibcugraph' and then 'cugraph' targets
Looks like you removed `libcugraph_etl` here, but it's still built by default below.  I don't have a preference for building it by default or not, but just would like the help to be accurate.

2023-10-11 19:07 UTC, rlratzel approved these changes

2023-10-12 14:22 UTC, BradReesWork commented
/merge

2023-10-12 14:22 UTC, merged