Download `xml` docs artifact through CloudFront endpoint
rapidsai/cugraph pull request #3955
Opened 2023-10-24 17:26 UTC by AyodeAwe

The previous `aws s3 cp` command failed for developers who tried to run `build_docs.sh` locally. This PR addresses the issue by providing a CDN URL that delivers the tarred XML artifact.

2023-10-24 18:18 UTC, ajschmidt8 requested changes

2023-10-26 17:14 UTC, AyodeAwe commented on ci/build_docs.sh
> +  curl -O "https://d1664dvumjb44w.cloudfront.net/${PROJECT}/xml_tar/${RAPIDS_VERSION}/xml.tar.gz" && tar -xzf "xml.tar.gz" -C "${TMP_DIR}"
I stand corrected. Done.

2023-10-26 17:18 UTC, AyodeAwe commented
The docs failure issue is covered [here](https://nvidia.slack.com/archives/CCE7L5XT3/p1698339152882479?thread_ts=1698193256.710169&cid=CCE7L5XT3).

2023-10-26 19:25 UTC, ajschmidt8 approved these changes

2023-10-27 07:25 UTC, merged