Update to CCCL 2.2.0.
rapidsai/cugraph pull request #4052
Opened 2023-12-07 18:03 UTC by bdice

This PR updates cuGraph to CCCL 2.2.0. Do not merge until all of RAPIDS is ready to update.

Replaces #3516.

2023-12-18 15:34 UTC, bdice commented on fetch_rapids.cmake
> +set(rapids-cmake-branch cuco-cccl-2.2.0)
I will revert this before merging. Depends on https://github.com/NVIDIA/cuCollections/pull/404/ merging, and rapids-cmake being updated to use that commit in `versions.json`.

2023-12-18 15:34 UTC, bdice commented on ci/build_cpp.sh
> +LIBRMM_CHANNEL=$(rapids-get-pr-conda-artifact rmm 1404 cpp)
I will revert changes to CI scripts that use upstream artifacts before merging.

2023-12-18 20:05 UTC, vyasr requested changes

2023-12-18 20:05 UTC, vyasr commented on cpp/CMakeLists.txt
> +# This ensures that libraries can be overridden for testing.
If this is the reason why this ordering exists in raft/cugraph*/cuml*, we probably want to document and educate rather than actually use this order.

2023-12-18 21:53 UTC, vyasr commented on cpp/CMakeLists.txt
> +# This ensures that libraries can be overridden for testing.
We decided offline that the testing ability was important and we're OK with double-bundling until rapids-core-dependencies exists.

2023-12-18 21:54 UTC, vyasr approved these changes

2023-12-19 05:19 UTC, bdice commented
I don't have a way to test this build in CI with the private cugraph-ops build from https://github.com/rapidsai/cugraph-ops/pull/580. I see there is an error here, but it's because we haven't merged that PR yet. https://github.com/rapidsai/cugraph/actions/runs/7229496902/job/19701156504?pr=4052#step:7:641

I have tested this locally and it should be fine. We may have to admin-merge this PR depending on the build order / timing of the other repositories, since it's so far down the dependency tree (rmm -> raft -> cugraph-ops -> cugraph).

Full error below: it comes from `thrust_create_target` with an outdated `cugraph-ops-config.cmake`. This is fixed in https://github.com/rapidsai/cugraph-ops/pull/580.
```
      -- Found Thrust: /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/rapids/cmake/thrust/thrust-config.cmake (found suitable exact version "2.2.0.0")
      -- Found CCCL: /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/rapids/cmake/cccl/cccl-config.cmake (found version "2.2.0.0")
      -- Found rmm: /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/cmake/rmm/rmm-config.cmake (found version "24.02.0")
      -- Found cuco: /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/cmake/cuco/cuco-config.cmake (found version "0.0.1")
      -- Found OpenMP_CXX: -fopenmp (found version "4.5")
      -- Found OpenMP: TRUE (found version "4.5")
      -- Found raft: /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/cmake/raft/raft-config.cmake (found version "24.02.0")
      CMake Error at /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/targets/sbsa-linux/lib/cmake/thrust/thrust-config.cmake:225 (message):
        The version of CUB found by CMake is not compatible with this release of
        Thrust.  CUB is now included in the CUDA Toolkit, so you no longer need to
        use your own checkout of CUB.  Pass IGNORE_CUB_VERSION_CHECK to
        thrust_create_target to ignore.  (CUB 2.2.0.0, Thrust 2.0.1.0).
      Call Stack (most recent call first):
        /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/cmake/cugraph-ops/cugraph-ops-config.cmake:150 (thrust_create_target)
        /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/cmake/cugraph/cugraph-dependencies.cmake:34 (find_package)
        /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/cmake/cugraph/cugraph-config.cmake:72 (include)
        CMakeLists.txt:46 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
```

2023-12-19 16:23 UTC, raydouglass approved these changes

2023-12-19 23:32 UTC, vyasr commented
/merge

2023-12-20 01:51 UTC, merged