Update SG notebook to handle a handle a couple of cases where the current notebook run fails
rapidsai/cugraph pull request #4169
Opened 2024-02-13 18:41 UTC by naimnv

Changes:
For graphs without weights, run bfs.
For graphs without node id 0, peek an existing node id for BFS and SSP

2024-02-13 19:05 UTC, naimnv commented
/ok to test

2024-02-13 22:32 UTC, naimnv commented
/ok to test

2024-02-13 22:39 UTC, naimnv commented
/ok to test

2024-02-14 15:33 UTC, BradReesWork approved these changes

2024-02-14 15:40 UTC, acostadon commented on notebooks/cugraph_benchmarks/synth_release.ipynb
> +    "| Naim, Md      | 2/12/2024  | Modified            | 24.04 nightly   | RTX A6000, CUDA 12.0   |\n"
This should say 2xA6000 if that is what you used to test multi-GPU.

2024-02-14 15:41 UTC, acostadon requested changes
Changes look great
Did you test this on multi-GPU, if so please note what GPU's were used in the header.

2024-02-14 18:45 UTC, acostadon approved these changes
Looks great

2024-02-14 18:47 UTC, naimnv commented
> Changes look great Did you test this on multi-GPU, if so please note what GPU's were used in the header.

For `synth_release_single_node_multi_gpu.ipynb`  the hardware is now `2xRTX A600`
For synth_release_single_gpu.ipynb the hardware is  `RTX A600`

2024-02-14 18:47 UTC, naimnv commented
/ok to test

2024-02-15 13:47 UTC, BradReesWork commented
/merge

2024-02-15 13:47 UTC, merged