Add degrees to C API
rapidsai/cugraph pull request #4212
Opened 2024-03-04 22:31 UTC by ChuckHastings

Add new method `cugraph_degrees` to the C API to compute and return the degrees of vertices.

2024-03-07 19:52 UTC, rlratzel submitted a review, later dismissed

2024-03-07 19:54 UTC, rlratzel commented
This LGTM.  I'm fine if we want to add the remaining updates needed to PLC, then the updates to the MG python code all to this PR if it's easier.

2024-03-11 16:32 UTC, seunghwak approved these changes
LGTM (C/C++ part)

2024-03-11 18:26 UTC, rlratzel requested changes
Thanks!  I only reviewed the python code and I have a few requests and questions.

2024-03-11 22:02 UTC, jnke2016 commented on python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py
> +        and degrees for the entire set of vertices. If vertex_subset is provided,
That was a typo. It was meant to be `or` not `and`.

2024-03-11 22:06 UTC, jnke2016 commented on python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py
> +                vertex_subset_type = self.input_df.dtypes[0]
Thanks for letting me know

2024-03-11 22:51 UTC, jnke2016 commented on python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py
> +    def degrees_function(self, vertex_subset=None, degree_type="in_degree"):
Sure. I added them

2024-03-12 23:00 UTC, rlratzel approved these changes

2024-03-12 23:01 UTC, rlratzel commented
/merge

2024-03-12 23:01 UTC, merged