Enable pytest failures on warnings from cudf
rapidsai/cugraph pull request #4223
Opened 2024-03-08 03:04 UTC by mroeschke

In 24.04, cudf issues a FutureWarning when using positional indexing with `__getitem__`. The change here is to use `iloc` instead.

Additionally the test suite will now fail when a warning comes from cudf as apart of https://github.com/rapidsai/build-planning/issues/26

2024-03-08 13:01 UTC, acostadon commented on python/cugraph/pytest.ini
License update needed

2024-03-08 13:48 UTC, acostadon requested changes
What is the schedule to merge this?
Is it for 24.04?

2024-03-08 17:36 UTC, mroeschke commented
> What is the schedule to merge this? What is the schedule to merge this?
Is it for 24.04?

This is not critical for 24.04. Fine to de-prioritize over other PRs

2024-03-11 18:42 UTC, rlratzel approved these changes
Thank you very much!
We should have treated cudf warnings as test failures long ago.

2024-03-11 18:46 UTC, BradReesWork commented
All - can we get this is as soon as possible.  while the warnings do not stop an analytic, is still looks bad on us to even have warrings

2024-03-11 18:49 UTC, acostadon approved these changes
Looks great !!!

2024-03-15 16:53 UTC, BradReesWork commented
@mroeschke there is a merge conflict

2024-03-17 22:11 UTC, BradReesWork commented
/merge

2024-03-17 22:11 UTC, merged