nujndkvfeekBug post processing
rapidsai/cugraph pull request #4329
Opened 2024-04-09 17:06 UTC by seunghwak

2024-04-09 18:11 UTC, alexbarghi-nv commented
I'm tentatively approving this, will give final approval once I test

2024-04-16 18:51 UTC, ChuckHastings approved these changes

2024-04-16 18:51 UTC, ChuckHastings commented
Should be able to merge once @alexbarghi-nv approves.  Let us know how testing goes.

2024-04-18 03:11 UTC, alexbarghi-nv commented
I'm seeing a bug where memory addresses are getting corrupted.  Not sure if it's on my end or if it's something this PR introduced.  Still troubleshooting.  Will post a MRE if I am able to isolate it to something in this PR.

2024-04-18 03:53 UTC, seunghwak commented
> I'm seeing a bug where memory addresses are getting corrupted. Not sure if it's on my end or if it's something this PR introduced. Still troubleshooting. Will post a MRE if I am able to isolate it to something in this PR.

Have you set do_expensive_check to true?

2024-04-18 17:23 UTC, alexbarghi-nv commented
> > I'm seeing a bug where memory addresses are getting corrupted. Not sure if it's on my end or if it's something this PR introduced. Still troubleshooting. Will post a MRE if I am able to isolate it to something in this PR.
> 
> Have you set do_expensive_check to true?

I'll try that

2024-04-18 18:08 UTC, alexbarghi-nv commented
It looks like it may be something I introduced in my PR

2024-04-18 18:08 UTC, alexbarghi-nv commented
I couldn't replicate this with only the code in this PR

2024-04-18 19:13 UTC, alexbarghi-nv commented
> I'm seeing a bug where memory addresses are getting corrupted. Not sure if it's on my end or if it's something this PR introduced. Still troubleshooting. Will post a MRE if I am able to isolate it to something in this PR.

I have now isolated and fixed the bug.  It was an issue with data being improperly copied in my PR.

2024-04-18 20:55 UTC, alexbarghi-nv requested changes
Small change request.  Otherwise good.

2024-04-18 20:55 UTC, alexbarghi-nv commented on cpp/src/c_api/uniform_neighbor_sampling.cpp
> +              edge_label ? edge_label->size() : size_t{1},
```suggestion
              (label_list_ == nullptr) ? size_t{1} : label_list_->size_,
```

2024-04-18 20:55 UTC, alexbarghi-nv commented on cpp/src/c_api/uniform_neighbor_sampling.cpp
> +                                         edge_label ? edge_label->size() : size_t{1},
```suggestion
                                         (label_list_ == nullptr) ? size_t{1} : label_list_->size_,
```

2024-04-18 21:49 UTC, alexbarghi-nv commented on cpp/src/c_api/uniform_neighbor_sampling.cpp
> +              edge_label ? edge_label->size() : size_t{1},
never mind, I think this is ok as is

2024-04-18 21:49 UTC, alexbarghi-nv commented on cpp/src/c_api/uniform_neighbor_sampling.cpp
> +                                         edge_label ? edge_label->size() : size_t{1},
same here, resolving

2024-04-18 22:16 UTC, alexbarghi-nv approved these changes
Approved, but we can't integrate this with dask+Python until that code gets refactored (#4358)

This is ready to go for the new distributed sampling framework, though, which just uses `pylibcugraph` and NCCL.

👍

2024-04-19 17:11 UTC, alexbarghi-nv commented
/merge

2024-04-19 17:11 UTC, merged