WIP: bump NCCL floor to 2.18.1.1
rapidsai/cugraph pull request #4661
Opened 2024-09-20 21:47 UTC by jameslamb

## Description

Contributes to https://github.com/rapidsai/build-planning/issues/102

Some RAPIDS libraries are using `ncclCommSplit()`, which was introduced in `nccl==2.18.1.1`. This is part of a series of PRs across RAPIDS updating libraries' pins to `nccl>=2.18.1.1` to ensure they get a new-enough version that supports that.

2024-09-24 17:13 UTC, vyasr requested changes
cugraph also ought to be able to rely on raft for its NCCL handling rather than doing anything on its own AFAICT. It does use some raft APIs that accept NCCL types directly as arguments, but I still think that's OK.

2024-09-24 18:32 UTC, jameslamb commented
I'm not convinced that `cugraph` could/should drop its NCCL dependency and only get it transitively through raft.

It has some direct uses, like these:

https://github.com/rapidsai/cugraph/blob/7e058e2961b5b8be05877282d26051f36dd73c53/cpp/include/cugraph/mtmg/instance_manager.hpp#L52

https://github.com/rapidsai/cugraph/blob/7e058e2961b5b8be05877282d26051f36dd73c53/cpp/include/cugraph/mtmg/resource_manager.hpp#L200

As well as others in tests and examples:

https://github.com/rapidsai/cugraph/blob/7e058e2961b5b8be05877282d26051f36dd73c53/cpp/tests/mtmg/threaded_test.cu#L41

https://github.com/rapidsai/cugraph/blob/7e058e2961b5b8be05877282d26051f36dd73c53/cpp/tests/mtmg/threaded_test_jaccard.cu#L41

https://github.com/rapidsai/cugraph/blob/7e058e2961b5b8be05877282d26051f36dd73c53/cpp/tests/mtmg/threaded_test_louvain.cu#L41

https://github.com/rapidsai/cugraph/blob/7e058e2961b5b8be05877282d26051f36dd73c53/cpp/examples/developers/graph_operations/CMakeLists.txt#L28

https://github.com/rapidsai/cugraph/blob/7e058e2961b5b8be05877282d26051f36dd73c53/cpp/examples/developers/graph_operations/CMakeLists.txt#L38

Those look like direct-enough uses that `cugraph` should have its own pinnings, in my opinion.

2024-09-24 18:45 UTC, vyasr commented
I agree, those are direct uses. In that case, though, the files should be including nccl.h rather than relying on it being transitively included by raft's std_comms.h.

2024-09-24 19:34 UTC, ChuckHastings approved these changes

2024-09-24 19:44 UTC, jameslamb commented
> the files should be including nccl.h rather than relying on it being transitively included by raft's std_comms.h.

Agreed! Pushed https://github.com/rapidsai/cugraph/pull/4661/commits/7fca13ffb6ad20230c478a0009e3cc504183f7dc adding that.

Maybe in the future we can explore using `include-what-you-use` (https://github.com/include-what-you-use/include-what-you-use) in CI. I found from search that you'd tried that last year: https://github.com/rapidsai/cudf/issues/581#issuecomment-1362133285, maybe at some point we can look into it again.

2024-09-24 23:24 UTC, vyasr approved these changes

2024-09-25 02:21 UTC, jakirkham approved these changes

2024-09-25 04:25 UTC, jameslamb commented
/merge

2024-09-25 04:25 UTC, merged