Adds utility scripts and initial docs for managing multi-GPU Dask clusters for cuGraph
rapidsai/cugraph pull request #4838
Opened 2024-12-20 19:01 UTC by rlratzel

This PR adds utility scripts and initial docs for managing multi-GPU Dask clusters for cuGraph, aimed at helping the situation described in [this issue](https://github.com/rapidsai/cugraph/issues/4831).

These scripts are taken from internal tools used for MNMG testing and have been modified to be more generalized for use by the community.

2025-01-03 15:53 UTC, acostadon requested changes
Other than copyright looks great

2025-01-03 15:53 UTC, acostadon commented on scripts/dask/run-dask-process.sh
> +# Copyright (c) 2024, NVIDIA CORPORATION.
```suggestion
# Copyright (c) 2024-2025, NVIDIA CORPORATION.
```

2025-01-03 15:53 UTC, acostadon commented on scripts/dask/wait_for_workers.py
> +# Copyright (c) 2024, NVIDIA CORPORATION.
```suggestion
# Copyright (c) 2024-2025, NVIDIA CORPORATION.
```

2025-01-03 16:01 UTC, BradReesWork approved these changes
Once Copyright is fixed, looks good

2025-01-03 16:12 UTC, jnke2016 commented on scripts/dask/README.md
> + bash$ run-dask-process.sh scheduler workers
I am not sure if we should add more details in the README regarding the different communication framework supported like `--tcp`, `--ucx`, `--ucxib`

2025-01-03 16:53 UTC, rlratzel commented on scripts/dask/README.md
> + bash$ run-dask-process.sh scheduler workers
I added those details, thanks.

2025-01-03 16:55 UTC, acostadon approved these changes

2025-01-06 21:54 UTC, jnke2016 approved these changes
Thanks for adding more description about the other available options. Looks good to me

2025-01-07 02:56 UTC, rlratzel commented
/merge

2025-01-07 02:56 UTC, merged